# Generated by Django 5.0.7 on 2024-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
